apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server-repo
  namespace: example
spec:
  interval: 2m
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: example
spec:
  targetNamespace: default
  releaseName: metrics-server
  interval: 2m
  install:
    createNamespace: false
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server-repo
        namespace: example
  valuesFrom:
    - name: metrics-server-values
      kind: ConfigMap
