image:
  repository: ghcr.io/revacomm-pwheeler/fluent-bit-grafana-loki
  tag: latest
logLevel: info
extraVolumes:
  - hostPath:
      path: /var/log/flb-storage/
      type: DirectoryOrCreate
    name: flb-storage
extraVolumeMounts:
  - mountPath: /var/log/flb-storage/
    name: flb-storage
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On
        Plugins_File /fluent-bit/etc/plugins.conf
  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name            tail
        Tag             kube.*
        Path            /var/log/containers/*.log
        Parser          docker
        DB              /var/log/flb-storage/flb_kube.db
        Skip_Long_Lines On
  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name      kubernetes
        Match     kube.*
        Merge_Log Off
        Keep_Log  On
        # Disable pod annotation configuration overrides
        K8S-Logging.Parser  Off
        K8S-Logging.Exclude Off
  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        name                   loki
        match                  kube.*
        host                   loki.logging.svc.cluster.local
        port                   3100
        auto_kubernetes_labels off
        labels                 job=fluent-bit, stream=$stream, container=$kubernetes['container_name'], node=$kubernetes['host'], instance=$kubernetes['pod_name'], namespace=$kubernetes['namespace_name'], labels=$kubernetes['labels']
        remove_keys            kubernetes
        workers                1
        # network configuration
        # net.dns.mode               TCP
        # net.connect_timeout        5
        # net.keepalive              on
        # net.keepalive_idle_timeout 10
    
    [OUTPUT]
        Name                 grafana-loki
        Match                kube.*
        Url                  http://loki.logging.svc.cluster.local:3100/api/prom/push
        BatchWait            1
        BatchSize            1048576
        Labels               {job="grafana"}
        RemoveKeys           kubernetes
        AutoKubernetesLabels false
        LabelMapPath         /fluent-bit/etc/labelmap.json
        LineFormat           json
        LogLevel             warn
  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

  extraFiles:
    labelmap.json: |
      {
        "kubernetes": {
          "container_name": "container",
          "host": "node",
          "labels": "labels",
          "namespace_name": "namespace",
          "pod_name": "instance"
        },
        "stream": "stream"
      }
    plugins.conf: |
      [PLUGINS]
          Path /usr/lib/out_grafana_loki.so
